### ISSUE TITLE
wrong method name in chapter Serializer

### ISSUE THREAD

**Issue by thebesttv** [oblac/jodd-json-site#1]
Hi, I found that the `use` method in the sample code of the section [JSON Type Serializers](https://json.jodd.org/serializer#json-type-serializers) is actually named `withSerializer​` in the source code. Maybe that's a typo in the doc?

**Comment by neroux** [comment]
@thebesttv, not sure if Corona could serve as excuse for the delay in responding, but you are absolutely right. There's a request at #3 and I hope @igr can merge it soon :)

**Comment by igr** [comment]
Dang. I just realized I am not getting notifications for the website repos. All merged!
